version: '3.8'

services:
  url-shorter:
    build: ./
    command: ./wait-for-postgres.sh db ./url-shorter
    ports:
      - 8083:8083
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432