env: "local"
storage_path: "./"
http_server:
  adress: "localhost:8083"
  port: "8083"
  timeout: 4s
  idle_timeout: 60s

db:
  host: "db"
  port: "5432"
  username: "postgres"
  dbname: "postgres"  
  sslmode: "false"

